#!/bin/bash
COMPOSE='docker-compose -f Docker/docker-compose.yml'

if [[ -z "$1" ]]
then
    echo "No command specified. Please try again with either 'up', 'down', 'build', or 'run'"
    exit 0
fi

if [[ "$1" = "up" ]]
then
    $COMPOSE up
elif [[ "$1" = "down" ]]
then
    $COMPOSE down
elif [[ "$1" = "build" ]]
then
    rm -rf build/* && cd build && cmake .. && make
elif [[ "$1" = "run" ]]
then
    rm -rf build/* && cd build && cmake .. && make && bin/myexample && cd ../
elif [[ "$1" = "install" ]]
then
    git submodule init
    git submodule update
fi
