version: '3.9'
services:
  compile:
    image: sarahjabado/cardinal-compiler:1.0.3
    volumes:
      - ../:/app
  gameserver:
    build: 
      context: ../
      dockerfile: ./Docker/GameServer/Dockerfile
    ports:
      - '7777:7777'
    volumes:
      - ../build/bin:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IDENTIFIER: "GameServer"
      IS_LISTENER: "TRUE"
      POST: 7777
      BIND_IP: 0.0.0.0
    restart: on-failure
    depends_on:
      compile:
        condition: service_completed_successfully
      redis:
        condition: service_started
      # - worker
    links:
      - redis
  worker:
    build: 
      context: ../
      dockerfile: ./Docker/Worker/Dockerfile
    volumes:
      - ../build/bin:/app
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      IDENTIFIER: "Worker"
      QUEUE: "default"
      IS_LISTENER: "FALSE"
    restart: on-failure
    depends_on:
      compile:
        condition: service_completed_successfully
      redis:
        condition: service_started
    links:
      - redis
  redis:
    image: redis/redis-stack-server:latest
    depends_on:
      compile:
        condition: service_completed_successfully
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel verbose --protected-mode no